# exception_throws_1
 
